# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 20:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCensoDoVolei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Imagem', models.FileField(upload_to=b'')),
                ('Ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BannerRedeDesconto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Imagem', models.FileField(upload_to=b'')),
                ('Ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaCensoDoVolei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaConteudoExclusivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaExperiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaRedeDeDesconto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CensoDoVolei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Detalhe', models.CharField(blank=True, max_length=50, null=True)),
                ('Thumb', models.FileField(blank=True, help_text='Alta Resolu\xe7\xe3o, 16x9, PNG ou JPG', null=True, upload_to=b'')),
                ('Topo', models.FileField(help_text='Alta Resolu\xe7\xe3o, 16x9, PNG ou JPG', upload_to=b'')),
                ('Conteudo', tinymce.models.HTMLField(blank=True, null=True)),
                ('DataPublicacao', models.DateField(blank=None, null=True)),
                ('Publicar', models.BooleanField(default=False)),
                ('ImagemCarrossel', models.FileField(blank=True, help_text='Alta Resolu\xe7\xe3o, 16x9, PNG ou JPG', null=True, upload_to=b'')),
                ('Link', models.CharField(max_length=1000)),
                ('Ativo', models.BooleanField(default=False)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitecbv.CategoriaCensoDoVolei')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConteudoExclusivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Detalhe', models.CharField(blank=True, max_length=50, null=True)),
                ('Thumb', models.FileField(blank=True, help_text='Alta Resolu\xe7\xe3o, 16x9, PNG ou JPG', null=True, upload_to=b'')),
                ('Topo', models.FileField(help_text='Alta Resolu\xe7\xe3o, 16x9, PNG ou JPG', upload_to=b'')),
                ('Conteudo', tinymce.models.HTMLField(blank=True, null=True)),
                ('DataPublicacao', models.DateField(blank=None, null=True)),
                ('Publicar', models.BooleanField(default=False)),
                ('Destaque', models.BooleanField(default=False)),
                ('ImagemCarrossel', models.FileField(blank=True, help_text='Alta Resolu\xe7\xe3o, 16x9, PNG ou JPG', null=True, upload_to=b'')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitecbv.CategoriaConteudoExclusivo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Detalhe', models.CharField(blank=True, max_length=50, null=True)),
                ('Thumb', models.FileField(blank=True, help_text='Alta Resolu\xe7\xe3o, 16x9, PNG ou JPG', null=True, upload_to=b'')),
                ('Topo', models.FileField(help_text='Alta Resolu\xe7\xe3o, 16x9, PNG ou JPG', upload_to=b'')),
                ('Conteudo', tinymce.models.HTMLField(blank=True, null=True)),
                ('DataPublicacao', models.DateField(blank=None, null=True)),
                ('Publicar', models.BooleanField(default=False)),
                ('ImagemCarrossel', models.FileField(blank=True, help_text='Alta Resolu\xe7\xe3o, 16x9, PNG ou JPG', null=True, upload_to=b'')),
                ('Destaque', models.BooleanField(default=False)),
                ('Link', models.CharField(max_length=1000)),
                ('Ativo', models.BooleanField(default=False)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitecbv.CategoriaExperiencia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfosAdicionaisUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrocompleto', models.BooleanField(default=False)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('tipodocumento', models.CharField(choices=[('CPF', 'CPF'), ('PAS', 'Passaporte')], default='CPF', max_length=3)),
                ('ufed', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=15, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('modalidade_favorita', models.CharField(choices=[('VQ', 'Volei de Quadra'), ('VP', 'Volei de Praia')], default='VQ', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=15)),
                ('Sexo', models.CharField(max_length=1)),
                ('Foto', models.FileField(help_text='300x300 PNG ou JPG', upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='RedeDeDesconto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Detalhe', models.CharField(blank=True, max_length=50, null=True)),
                ('Thumb', models.FileField(blank=True, help_text='Alta Resolu\xe7\xe3o, 16x9, PNG ou JPG', null=True, upload_to=b'')),
                ('Topo', models.FileField(help_text='Alta Resolu\xe7\xe3o, 16x9, PNG ou JPG', upload_to=b'')),
                ('Conteudo', tinymce.models.HTMLField(blank=True, null=True)),
                ('DataPublicacao', models.DateField(blank=None, null=True)),
                ('Publicar', models.BooleanField(default=False)),
                ('ImagemCarrossel', models.FileField(blank=True, help_text='Alta Resolu\xe7\xe3o, 16x9, PNG ou JPG', null=True, upload_to=b'')),
                ('Link', models.CharField(max_length=1000)),
                ('Ativo', models.BooleanField(default=False)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitecbv.CategoriaRedeDeDesconto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=15)),
                ('Logo', models.FileField(help_text='300x300 PNG ou JPG', upload_to=b'')),
            ],
        ),
        migrations.AddField(
            model_name='infosadicionaisusuario',
            name='jogador_favorito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infos_jogador_favorito', to='sitecbv.Jogador'),
        ),
        migrations.AddField(
            model_name='infosadicionaisusuario',
            name='jogadora_favorita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infos_jogadora_favorita', to='sitecbv.Jogador'),
        ),
        migrations.AddField(
            model_name='infosadicionaisusuario',
            name='jogadoras_secundarias_femininas',
            field=models.ManyToManyField(related_name='infos_jogadoras_secundarias_femininas', to='sitecbv.Jogador'),
        ),
        migrations.AddField(
            model_name='infosadicionaisusuario',
            name='jogadores_secundario_masculinos',
            field=models.ManyToManyField(related_name='infos_jogadores_secundario_masculinos', to='sitecbv.Jogador'),
        ),
        migrations.AddField(
            model_name='infosadicionaisusuario',
            name='time_favorito_feminino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos_time_favorito_feminino', to='sitecbv.Time'),
        ),
        migrations.AddField(
            model_name='infosadicionaisusuario',
            name='time_favorito_masculino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos_time_favorito_masculino', to='sitecbv.Time'),
        ),
        migrations.AddField(
            model_name='infosadicionaisusuario',
            name='times_secundarios_feminino',
            field=models.ManyToManyField(related_name='infos_times_secundarios_feminino', to='sitecbv.Time'),
        ),
        migrations.AddField(
            model_name='infosadicionaisusuario',
            name='times_secundarios_masculino',
            field=models.ManyToManyField(related_name='infos_times_secundarios_masculino', to='sitecbv.Time'),
        ),
        migrations.AddField(
            model_name='infosadicionaisusuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
