# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0002_auto_20170510_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Topo', models.FileField(help_text='Alta Resolu\xe7\xe3o, 16x9, PNG ou JPG', upload_to=b'')),
                ('Conteudo', tinymce.models.HTMLField(blank=True, null=True)),
                ('Publicar', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='infosadicionaisusuario',
            name='cadastrocompleto',
            field=models.BooleanField(default=False, verbose_name='Cadastro Completo'),
        ),
        migrations.AlterField(
            model_name='infosadicionaisusuario',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Endere\xe7o'),
        ),
        migrations.AlterField(
            model_name='infosadicionaisusuario',
            name='numero',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='N\xfamero'),
        ),
        migrations.AlterField(
            model_name='infosadicionaisusuario',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pa\xeds'),
        ),
        migrations.AlterField(
            model_name='infosadicionaisusuario',
            name='tipodocumento',
            field=models.CharField(choices=[('CPF', 'CPF'), ('PAS', 'Passaporte')], default='CPF', max_length=3, verbose_name='Tipo de Documento'),
        ),
    ]
