# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 19:26
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0003_auto_20170511_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriacensodovolei',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='Nome', unique=True),
        ),
        migrations.AddField(
            model_name='categoriaconteudoexclusivo',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='Nome', unique=True),
        ),
        migrations.AddField(
            model_name='categoriaexperiencia',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='Nome', unique=True),
        ),
        migrations.AddField(
            model_name='categoriaredededesconto',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='Nome', unique=True),
        ),
        migrations.AlterField(
            model_name='censodovolei',
            name='Conteudo',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Conte\xfado'),
        ),
        migrations.AlterField(
            model_name='censodovolei',
            name='DataPublicacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Publica\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='censodovolei',
            name='Titulo',
            field=models.CharField(max_length=50, verbose_name='T\xedtulo'),
        ),
        migrations.AlterField(
            model_name='conteudoexclusivo',
            name='Conteudo',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Conte\xfado'),
        ),
        migrations.AlterField(
            model_name='conteudoexclusivo',
            name='DataPublicacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Publica\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='conteudoexclusivo',
            name='ImagemCarrossel',
            field=models.FileField(blank=True, help_text='Alta Resolu\xe7\xe3o, 16x9, PNG ou JPG', null=True, upload_to=b'', verbose_name='Imagem Carrossel'),
        ),
        migrations.AlterField(
            model_name='conteudoexclusivo',
            name='Titulo',
            field=models.CharField(max_length=50, verbose_name='T\xedtulo'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='Conteudo',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Conte\xfado'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='DataPublicacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Publica\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='Titulo',
            field=models.CharField(max_length=50, verbose_name='T\xedtulo'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='Conteudo',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Conte\xfado'),
        ),
        migrations.AlterField(
            model_name='redededesconto',
            name='Conteudo',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Conte\xfado'),
        ),
        migrations.AlterField(
            model_name='redededesconto',
            name='DataPublicacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Publica\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='redededesconto',
            name='Titulo',
            field=models.CharField(max_length=50, verbose_name='T\xedtulo'),
        ),
    ]
