# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0004_auto_20170511_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='Sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='Sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
    ]
