# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0005_auto_20170517_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='Superliga',
            field=models.CharField(choices=[('SA', 'Super Liga A'), ('SB', 'Super Liga B')], default='SA', max_length=2),
        ),
    ]
