# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0006_time_superliga'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosadicionaisusuario',
            name='nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='ImagemCarrossel',
            field=models.FileField(blank=True, help_text='Alta Resolu\xe7\xe3o, 16x9, PNG ou JPG', null=True, upload_to=b'', verbose_name='Imagem Carrossel'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='Link',
            field=models.CharField(max_length=1000, verbose_name='Link Externo'),
        ),
        migrations.AlterField(
            model_name='infosadicionaisusuario',
            name='cpf',
            field=models.CharField(blank=True, help_text='Apenas n\xfameros', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='infosadicionaisusuario',
            name='ufed',
            field=models.CharField(blank=True, choices=[('FO', 'Fora do Brasil'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amap\xe1'), ('BA', 'Bahia'), ('CE', 'Cear\xe1'), ('DF', 'Distrito Federal'), ('ES', 'Esp\xedrito Santo'), ('GO', 'Goi\xe1s'), ('MA', 'Maranh\xe3o'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Par\xe1'), ('PB', 'Para\xedba'), ('PE', 'Pernambuco'), ('PI', 'Piau\xed'), ('PR', 'Paran\xe1'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rond\xf4nia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'S\xe3o Paulo'), ('TO', 'Tocantins')], max_length=50, null=True, verbose_name='UF'),
        ),
    ]
