# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0007_auto_20170525_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosadicionaisusuario',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='infosadicionaisusuario',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='infosadicionaisusuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
