# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0008_auto_20170525_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='censodovolei',
            name='Subtitulo',
            field=models.CharField(default='', max_length=140, verbose_name='Subt\xedtulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conteudoexclusivo',
            name='Subtitulo',
            field=models.CharField(default='', max_length=140, verbose_name='Subt\xedtulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencia',
            name='Subtitulo',
            field=models.CharField(default='', max_length=140, verbose_name='Subt\xedtulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redededesconto',
            name='Subtitulo',
            field=models.CharField(default='', max_length=140, verbose_name='Subt\xedtulo'),
            preserve_default=False,
        ),
    ]
