# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0009_auto_20170528_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerrededesconto',
            name='Imagem',
            field=models.FileField(blank=True, help_text='Alta Resolu\xe7\xe3o, 16x9, PNG ou JPG', null=True, upload_to=b''),
        ),
    ]
