# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0011_auto_20170528_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='censodovolei',
            name='Destaque',
            field=models.BooleanField(default=False),
        ),
    ]
