# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0012_censodovolei_destaque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannercensodovolei',
            name='Imagem',
        ),
        migrations.AddField(
            model_name='bannercensodovolei',
            name='Subtitulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
