# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0013_auto_20170530_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosadicionaisusuario',
            name='modalidade_favorita',
            field=models.CharField(choices=[('VQ', 'Volei de Quadra'), ('VP', 'Volei de Praia'), ('AM', 'Ambos')], default='VQ', max_length=2),
        ),
    ]
