# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0015_time_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerrededesconto',
            name='Imagem',
            field=models.FileField(blank=True, help_text='908x302 px, PNG ou JPG', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='censodovolei',
            name='ImagemCarrossel',
            field=models.FileField(blank=True, help_text='678x226 px, PNG ou JPG', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='censodovolei',
            name='Thumb',
            field=models.FileField(blank=True, help_text='170x200 px, PNG ou JPG', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='censodovolei',
            name='Topo',
            field=models.FileField(help_text='908x302 px, PNG ou JPG', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='conteudoexclusivo',
            name='ImagemCarrossel',
            field=models.FileField(blank=True, help_text='678x226 px, PNG ou JPG', null=True, upload_to=b'', verbose_name='Imagem Carrossel'),
        ),
        migrations.AlterField(
            model_name='conteudoexclusivo',
            name='Thumb',
            field=models.FileField(blank=True, help_text='170x200 px, PNG ou JPG', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='conteudoexclusivo',
            name='Topo',
            field=models.FileField(help_text='908x302 px, PNG ou JPG', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='ImagemCarrossel',
            field=models.FileField(blank=True, help_text='678x226 px, PNG ou JPG', null=True, upload_to=b'', verbose_name='Imagem Carrossel'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='Thumb',
            field=models.FileField(blank=True, help_text='170x200 px, PNG ou JPG', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='Topo',
            field=models.FileField(help_text='908x302 px, PNG ou JPG', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='programa',
            name='Topo',
            field=models.FileField(help_text='908x302 px, PNG ou JPG', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='redededesconto',
            name='ImagemCarrossel',
            field=models.FileField(blank=True, help_text='678x226 px, PNG ou JPG', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='redededesconto',
            name='Thumb',
            field=models.FileField(blank=True, help_text='170x200 px, PNG ou JPG', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='redededesconto',
            name='Topo',
            field=models.FileField(help_text='908x302 px, PNG ou JPG', upload_to=b''),
        ),
    ]
