# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0016_auto_20170606_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='redededesconto',
            name='Selo',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
