# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0017_redededesconto_selo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerExperiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Subtitulo', models.CharField(max_length=100)),
                ('Ativo', models.BooleanField()),
            ],
        ),
    ]
