# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0018_bannerexperiencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerConteudoExclusivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Subtitulo', models.CharField(max_length=100)),
                ('Ativo', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Banner Conte\xfado Exclusivo',
                'verbose_name_plural': 'Banneres Conte\xfado Exclusivo',
            },
        ),
        migrations.AlterModelOptions(
            name='bannerexperiencia',
            options={'verbose_name': 'Banner Experi\xeancia', 'verbose_name_plural': 'Banneres Experi\xeancias'},
        ),
    ]
