# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0019_auto_20170607_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censodovolei',
            name='Subtitulo',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Subt\xedtulo'),
        ),
        migrations.AlterField(
            model_name='censodovolei',
            name='Topo',
            field=models.FileField(blank=True, help_text='908x302 px, PNG ou JPG', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='conteudoexclusivo',
            name='Subtitulo',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Subt\xedtulo'),
        ),
        migrations.AlterField(
            model_name='conteudoexclusivo',
            name='Topo',
            field=models.FileField(blank=True, help_text='908x302 px, PNG ou JPG', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='Subtitulo',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Subt\xedtulo'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='Topo',
            field=models.FileField(blank=True, help_text='908x302 px, PNG ou JPG', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='redededesconto',
            name='Subtitulo',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Subt\xedtulo'),
        ),
        migrations.AlterField(
            model_name='redededesconto',
            name='Topo',
            field=models.FileField(blank=True, help_text='908x302 px, PNG ou JPG', null=True, upload_to=b''),
        ),
    ]
