# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0021_infosadicionaisusuario_receberinformacoesprograma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censodovolei',
            name='Detalhe',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='conteudoexclusivo',
            name='Detalhe',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='Detalhe',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='redededesconto',
            name='Detalhe',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
