# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0022_auto_20170608_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerrededesconto',
            name='Subtitulo',
            field=models.CharField(default='', max_length=100, verbose_name='T\xedtulo'),
        ),
    ]
