# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0023_bannerrededesconto_subtitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='Subtitulo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bannerrededesconto',
            name='Subtitulo',
            field=models.CharField(default='', max_length=100, verbose_name='Subt\xedtulo'),
        ),
    ]
