# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0024_auto_20170613_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redededesconto',
            name='Selo',
            field=models.FileField(blank=True, help_text='300x300 px, PNG ou JPG', null=True, upload_to=b''),
        ),
    ]
