# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0026_auto_20170616_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='Nome',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='time',
            name='Nome',
            field=models.CharField(max_length=30),
        ),
    ]
