# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0027_auto_20170619_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='Nome',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='time',
            name='Nome',
            field=models.CharField(max_length=35),
        ),
    ]
