# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0029_auto_20170619_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerconteudoexclusivo',
            name='Subtitulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bannerexperiencia',
            name='Subtitulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bannerrededesconto',
            name='Subtitulo',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Subt\xedtulo'),
        ),
        migrations.AlterField(
            model_name='censodovolei',
            name='ImagemCarrossel',
            field=models.FileField(blank=True, help_text='912x500 px, PNG ou JPG', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='conteudoexclusivo',
            name='ImagemCarrossel',
            field=models.FileField(blank=True, help_text='912x500 px, PNG ou JPG', null=True, upload_to=b'', verbose_name='Imagem Carrossel'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='ImagemCarrossel',
            field=models.FileField(blank=True, help_text='912x500 px, PNG ou JPG', null=True, upload_to=b'', verbose_name='Imagem Carrossel'),
        ),
        migrations.AlterField(
            model_name='redededesconto',
            name='ImagemCarrossel',
            field=models.FileField(blank=True, help_text='912x500 px, PNG ou JPG', null=True, upload_to=b''),
        ),
    ]
