# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0031_auto_20170619_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='Nenhum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='time',
            name='Nenhum',
            field=models.BooleanField(default=False),
        ),
    ]
