# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0032_auto_20170620_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100, verbose_name='T\xedtulo')),
                ('Subtitulo', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Subt\xedtulo')),
                ('ImagemCarrossel', models.FileField(help_text='912x500 px, PNG ou JPG', upload_to=b'', verbose_name='Imagem Carrossel')),
                ('Link', models.CharField(default='#', max_length=1000)),
                ('Ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='infosadicionaisusuario',
            name='legado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='infosadicionaisusuario',
            name='ufed',
            field=models.CharField(blank=True, choices=[('', '--------------'), ('FO', 'Fora do Brasil'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amap\xe1'), ('BA', 'Bahia'), ('CE', 'Cear\xe1'), ('DF', 'Distrito Federal'), ('ES', 'Esp\xedrito Santo'), ('GO', 'Goi\xe1s'), ('MA', 'Maranh\xe3o'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Par\xe1'), ('PB', 'Para\xedba'), ('PE', 'Pernambuco'), ('PI', 'Piau\xed'), ('PR', 'Paran\xe1'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rond\xf4nia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'S\xe3o Paulo'), ('TO', 'Tocantins')], max_length=50, null=True, verbose_name='UF'),
        ),
    ]
