# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0033_auto_20170704_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerhome',
            name='Link',
            field=models.CharField(default='#', help_text="Informe link completo como 'http://eusoudovolei.com.br/'", max_length=1000),
        ),
    ]
