# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0034_auto_20170704_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerhome',
            options={'verbose_name': 'Banner Home', 'verbose_name_plural': 'Banneres Home'},
        ),
    ]
