# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0035_auto_20170704_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.CharField(max_length=100)),
                ('Imagem', models.FileField(help_text='120x120 px, PNG ou JPG', upload_to=b'')),
                ('Ativo', models.BooleanField(default=False)),
                ('Ordem', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)])),
            ],
        ),
    ]
