# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0036_beneficio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficio',
            name='Descricao',
            field=models.CharField(max_length=100, verbose_name='Descri\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='Subtitulo',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
