# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-25 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecbv', '0037_auto_20170714_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosadicionaisusuario',
            name='modalidade_favorita',
            field=models.CharField(blank=True, choices=[('', '--------------'), ('VQ', 'Volei de Quadra'), ('VP', 'Volei de Praia'), ('AM', 'Ambos')], max_length=2, null=True),
        ),
    ]
